runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always

  - url: /(.*\.html)(.*)
    static_files: public/\1
    upload: public/(.*\.html)(.*)
    secure: always

  - url: /(.*\.(ttf|woff2|eot|woff))$
    static_files: public/\1
    upload: public/.*\.(ttf|woff2|eot|woff)$
    secure: always

  - url: /(.*\.(svg|jpeg|jpg))$
    static_files: public/\1
    upload: public/.*\.(svg|jpeg|jpg)$
    secure: always

  - url: /(.*\.(css|js|map))$
    static_files: public/\1
    upload: public/.*\.(css|js|map)$
    secure: always

  - url: /(.*\.(json|webmanifest|xml))$
    static_files: public/\1
    upload: public/.*\.(json|webmanifest|xml)$
    secure: always

  - url: /(.*)/?
    static_files: public/\1/index.html
    upload: public/(.*)/index.html
    secure: always

skip_files:
  - (?!^public)
